### ISSUE TITLE
逐个字母開頭的可能愛分無仝的parse

### ISSUE THREAD

**Issue by sih4sing5hong5** [thewayiam/ami_dict_crawler#3]
我佇掠`pyu`的時陣，拄著`WebDriverException`
我實際用網站，有時陣網頁嘛會死去
可能袂使佇仝一个parse共全部`a`,`i`…開頭的單詞攏掠落來
愛分開掠

我印象`scrapy`會當用無仝的`parse`函式佮無仝的參數，我才閣研究看覓

### 原本log
```
...
2017-03-31 17:20:05 [scrapy.extensions.logstats] INFO: Crawled 1 pages (at 0 pages/min), scraped 1653 items (at 4 items/min)
2017-03-31 17:20:19 [scrapy.core.scraper] ERROR: Spider error processing <GET http://e-dictionary.apc.gov.tw/pyu/Search.htm> (referer: None)
Traceback (most recent call last):
  File "/home/django/git/ami_dict_crawler/crawler.py", line 59, in parse
    EC.presence_of_element_located((By.XPATH, '//span[text()="%s"]' % term.text))
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/selenium/webdriver/support/expected_conditions.py", line 63, in __call__
    return _find_element(driver, self.locator)
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/selenium/webdriver/support/expected_conditions.py", line 332, in _find_element
    raise e
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/selenium/webdriver/support/expected_conditions.py", line 328, in _find_element
    return driver.find_element(*by)
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 756, in find_element
    'value': value})['value']
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=57.0.2987.110)
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 3.13.0-36-generic x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/django/git/ami_dict_crawler/crawler.py", line 62, in parse
    print(start_letter.text)
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 73, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 491, in _execute
    return self._parent.execute(command, params)
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/home/django/git/ami_dict_crawler/venv/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: no such session
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 3.13.0-36-generic x86_64)

2017-03-31 17:20:19 [scrapy.core.engine] INFO: Closing spider (finished)
2017-03-31 17:20:19 [scrapy.extensions.feedexport] INFO: Stored json feed (1654 items) in: data/pyu.json
2017-03-31 17:20:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 235,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 18906,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2017, 3, 31, 9, 20, 19, 144628),
 'item_scraped_count': 1654,
 'log_count/ERROR': 1,
 'log_count/INFO': 316,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/WebDriverException': 1,
 'start_time': datetime.datetime(2017, 3, 31, 3, 35, 52, 374452)}
2017-03-31 17:20:19 [scrapy.core.engine] INFO: Spider closed (finished)

real    344m33.165s
user    1m40.062s
sys     2m10.669s
```

**Comment by thewayiam** [comment]
沒有碰過，不過既然 log 寫跟 session 相關，可以試試每個詞都是獨立 session，只要 yield request 時給定一個不會重複的參數就好，[範例](https://github.com/g0v/councilor-voter-guide/blob/e594161ac4d6caf4353234dafb735b2f69f07e9d/crawler/ilcc/councilors.py#L28-L29)，[官網文件](https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#multiple-cookie-sessions-per-spider)
說不定可以順便解決 https://github.com/thewayiam/ami_dict_crawler/issues/2

**Comment by sih4sing5hong5** [comment]
我這馬共`掠目錄`佮`掠詞條`分開

https://github.com/Taiwanese-Corpus/ami_dict_crawler/blob/master/crawler.py#L45

毋過in會相搶driver
`掠a的parse_list`會影響著`掠e的parse_list`，造成`StaleElementReferenceException`

#### 試過的方法1
用`-s CONCURRENT_REQUESTS=1 -s CONCURRENT_REQUESTS_PER_DOMAIN=1 -s REACTOR_THREADPOOL_MAXSIZE=1`
限制一擺走一个，嘛是有錯誤

#### 試過的方法2
一个`parse`配一个`driver`，會出現`ElementNotVisibleException`

#### 佇想的方法3
這馬的想法是：改轉去這馬按呢，全部攏佇`parse`內底做，予伊莫multithread
`掠a開頭的詞了`、`掠e開頭的詞了`、…，分別重`driver.get`

**Comment by sih4sing5hong5** [comment]
#### 當佇走的方法3
https://github.com/Taiwanese-Corpus/ami_dict_crawler/blob/6ea84d3cd2a67aa5c28c9502b6c0440a369dfa3f/crawler.py

有時陣會拄著`ConnectionRefusedError: [Errno 111] Connection refused`

動態閣袂穩的網站誠歹掠 @@

**Comment by sih4sing5hong5** [comment]
#4 攏做好矣
